Repository pterm/pterm, pull requests merged in 2020-11, with the labels that each got.

#102 docs(examples): change length of tree example in demo
  _examples/demo/main.go
Labels: documentation

#103 refactor(theme): change white to default color in `Theme`
  theme.go
Labels: documentation, examples

#104 refactor(theme): change `ListTextStyle` to `BulletListTextStyle`
  bulletlist_printer.go
  theme.go
  theme_test.go
Labels: breaking

#110 feat: make printers return errors
  CONTRIBUTING.md
  bigtext_printer.go
  bulletlist_printer.go
  bulletlist_printer_test.go
  interface_live_printer.go
  interface_renderable_printer.go
  internal/test_utils.go
  progressbar.go
  progressbar_test.go
  pterm_benchmark_test.go
  spinner.go
  table_printer.go
  tree_printer.go
Labels: breaking

#111 feat: add `CenterPrinter`
  README.md
  _examples/center/main.go
  center_printer.go
  center_printer_test.go
Labels: feature

#117 docs(review): add review check file
  docs/REVIEW.md
  docs/SYMBOLS.md
Labels: documentation

#116 fix(centerprinter): make centerprinter func return pointer
  center_printer.go
Labels: breaking

#119 feat: add `PanelPrinter`
  _examples/panel/main.go
  bigtext_printer.go
  internal/max_text_width.go
  panel_printer.go
  panel_printer_test.go
Labels: feature

#123 docs: add documentation website
  docs/.nojekyll
  docs/README.md
  docs/_assets/asciinema.js
  docs/_assets/favicon.ico
  docs/_assets/images/pterm_logo.png
  docs/_assets/prism-command.js
  docs/_assets/prism-flags.js
  docs/_assets/style.css
  docs/_coverpage.md
  docs/_sidebar.md
  docs/contributing.md
  docs/docs/_docs.md
  docs/index.html
  docs/quick-start.md
  docs/sw.js
Labels: documentation

#134 refactor: make all printer names end with `Printer`
  _examples/tree/main.go
  bulletlist_printer.go
  bulletlist_printer_test.go
  print.go
  progressbar_printer.go
  progressbar_printer_test.go
  spinner_printer.go
  spinner_printer_test.go
  table_printer.go
  table_printer_test.go
  tree_printer.go
  tree_printer_test.go
Labels: breaking

#138 ci: fix unit test count glitch
  README.md
  _examples/bigtext/animation.svg
  _examples/bulletlist-custom/animation.svg
  _examples/bulletlist/animation.svg
  _examples/center/animation.svg
  _examples/demo/animation.svg
  _examples/disable-color/animation.svg
  _examples/header-custom/animation.svg
  _examples/header/animation.svg
  _examples/override-default-printers/animation.svg
  _examples/panel/README.md
  _examples/panel/animation.svg
  _examples/paragraph-custom/animation.svg
  _examples/paragraph/animation.svg
  _examples/prefix/animation.svg
  _examples/print-basic-text/animation.svg
  _examples/print-color-fade-multiple/animation.svg
  _examples/print-color-fade/animation.svg
  _examples/print-color-rgb/animation.svg
  _examples/print-with-color/animation.svg
  _examples/progressbar/animation.svg
  _examples/section/animation.svg
  _examples/spinner/animation.svg
  _examples/table/animation.svg
  _examples/theme/animation.svg
  _examples/tree/animation.svg
  ci/main.go
Labels: CI

#125 docs(pterm-sh): write docs
  .idea/conventionalCommit.xml
  README.md
  ci/main.go
  conventionalcommit.json
  docs/README.md
  docs/_assets/favicon.ico
  docs/_assets/images/pterm_logo.png
  docs/_assets/style.css
  docs/_coverpage.md
  docs/_sidebar.md
  docs/contributing.md
  docs/contributing/review-checks.md
  docs/contributing/writing-documentation-template.md
  docs/contributing/writing-documentation.md
  docs/docs/_docs.md
  docs/docs/functions/print.md
  docs/docs/intro.md
  docs/docs/override-default-printer.md
  docs/docs/printer/basictext.md
  docs/docs/printer/bigtext.md
  docs/docs/printer/bulletlist.md
  docs/docs/printer/center.md
  docs/docs/printer/header.md
  docs/docs/printer/panel.md
  docs/docs/printer/paragraph.md
  docs/docs/printer/progressbar.md
  docs/docs/printer/section.md
  docs/docs/printer/spinner.md
  docs/docs/printer/table.md
  docs/docs/printer/tree.md
  docs/docs/types/bulletlistitem.md
  docs/index.html
  docs/quick-start.md
Labels: documentation, feature

#146 Feat: add chart printer
  CONTRIBUTING.md
  _examples/barchart/main.go
  atoms.go
  atoms_test.go
  barchart.go
  barchart_test.go
  docs/contributing/writing-documentation.md
  docs/docs/printer/barchart.md
  theme.go
  theme_test.go
Labels: feature

#150 feat: add a `BoxPrinter` and add optional surrounding of Boxes in `PanelPrinter`
  _examples/box/main.go
  box_printer.go
  box_printer_test.go
  docs/_sidebar.md
  docs/docs/printer/box.md
  docs/docs/printer/panel.md
  panel_printer.go
  panel_printer_test.go
  theme.go
  theme_test.go
Labels: feature

#152 feat(boxprinter): add `WithHorizontalString` to `BoxPrinter`
  _examples/box/main.go
  box_printer.go
  box_printer_test.go
Labels: documentation
