Repository pterm/pterm, pull requests merged in 2020-10, with the labels that each got.

#2 feat: add pull request template
  .github/pull_request_template.md
  _examples/demo/main.go
Labels: documentation, enhancement

#3 docs: add sponsor button
  .github/FUNDING.yml
Labels: documentation, enhancement

#4 feat: add fatal to `PrefixPrinter`
  prefix_printer.go
Labels: enhancement

#5 feat: add `Progressbar`
  progressbar.go
Labels: enhancement

#7 feat: make progressbar configurable
  _examples/progressbar/main.go
  progressbar.go
Labels: enhancement

#17 feat: add `BarFiller` to `Progressbar`
  _examples/progressbar/main.go
  progressbar.go
Labels: enhancement

#19 Add tests
  benchmarks_test.go
  go.mod
  go.sum
  internal/collection.go
  print.go
  pterm_test.go
Labels: enhancement

#21 Add section printer
  _examples/section-default/main.go
  header_printer.go
  pterm_test.go
  section_printer.go
Labels: enhancement

#24 feat: add `ParagraphPrinter`
  CONTRIBUTING.md
  _examples/paragraph-custom/main.go
  _examples/paragraph/main.go
  paragraph_printer.go
  section_printer.go
Labels: enhancement

#25 docs(demo): add `SectionPrinter` to demo
  _examples/demo/main.go
Labels: enhancement

#27 feat: add `TablePrinter`
  CONTRIBUTING.md
  _examples/table/main.go
  table_printer.go
Labels: enhancement

#38 feat: add color fade example
  _examples/print-color-fade/main.go
Labels: enhancement

#41 feat: add HEX to RGB converter in `RGB`
  errors.go
  pterm_test.go
  rgb.go
Labels: enhancement

#42 feat: add csv table support
  table_printer.go
Labels: enhancement

#44 feat: add ability to disable output
  print.go
  pterm.go
  pterm_test.go
Labels: enhancement

#52 docs: add to do list to PR template
  .github/pull_request_template.md
Labels: documentation, enhancement

#53 feat: add BasicTextPrinter
  _examples/print-basic-text/main.go
  basic_text_printer.go
Labels: Hacktoberfest, enhancement

#49 Add theme support
  _examples/demo/main.go
  _examples/theme/main.go
  basic_text_printer.go
  color.go
  header_printer.go
  interface_live_printer.go
  interface_text_printer.go
  paragraph_printer.go
  prefix_printer.go
  progressbar.go
  pterm_benchmark_test.go
  pterm_test.go
  rgb.go
  section_printer.go
  spinner.go
  table_printer.go
  theme.go
Labels: breaking, enhancement

#58 Test coverage
  .golangci.yml
  CONTRIBUTING.md
  README.md
  basic_text_printer_test.go
  ci/main.go
  color_test.go
  header_printer_test.go
  internal/percentage.go
  internal/percentage_test.go
  internal/test_utils.go
  internal/with_boolean.go
  paragraph_printer_test.go
  prefix_printer.go
  prefix_printer_test.go
  print_test.go
  progressbar.go
  progressbar_test.go
  pterm_test.go
  rgb_test.go
  section_printer.go
  section_printer_test.go
  spinner.go
  spinner_test.go
  table_printer_test.go
  terminal_test.go
  theme.go
  theme_test.go
Labels: tests

#67 feat: add `BulletListPrinter`
  .golangci.yml
  _examples/bulletlist-custom/main.go
  _examples/bulletlist/main.go
  bulletlist_printer.go
  bulletlist_printer_test.go
  internal/remove_and_count_prefix.go
  theme.go
  theme_test.go
Labels: enhancement, examples, tests

#75 feat: add `BigTextPrinter`
  CONTRIBUTING.md
  _examples/bigtext/main.go
  _examples/demo/main.go
  bigtext_printer.go
  bigtext_printer_test.go
  go.mod
  go.sum
  internal/max_text_width.go
  internal/test_utils.go
  theme.go
  theme_test.go
Labels: enhancement

#90 docs(examples): redo demo
  _examples/demo/main.go
Labels: documentation

#93 feat: add support for enabling and disabling debug messages
  README.md
  _examples/prefix/main.go
  internal/test_utils.go
  prefix_printer.go
  prefix_printer_test.go
  pterm.go
  pterm_test.go
  theme.go
  theme_test.go
Labels: feature

#94 feat: add tree list
  _examples/bulletlist/main.go
  _examples/demo/main.go
  bulletlist_printer.go
  bulletlist_printer_test.go
Labels: breaking, feature

#96 feat: add option to disable and enable colors
  _examples/disable-color/main.go
  color.go
  color_test.go
Labels: feature

#97 Feat/add tree list
  README.md
  _examples/tree/main.go
  bulletlist_printer.go
  theme.go
  theme_test.go
  tree_printer.go
  tree_printer_test.go
Labels: feature
