Repository pterm/pterm, pull requests merged in 2023-07, with the labels that each got.

#533 refactor: use WithBoolean on multiselect printer
  interactive_multiselect_printer.go
Labels: refactor

#530 feat: add filter option for `select`
  interactive_select_printer.go
  interactive_select_printer_test.go
Labels: feature

#539 fix: fixed area on Windows
  go.mod
  go.sum
Labels: critical, fix
