Repository pterm/pterm, pull requests merged in 2023-04, with the labels that each got.

#476 docs(README): improved readme
  .github/workflows/go.yml
  README.md
Labels: documentation

#480 feat(logger): added pretty structured logger
  _examples/demo/demo/main.go
  _examples/logger/custom-key-styles/main.go
  _examples/logger/default/main.go
  _examples/logger/demo/main.go
  _examples/logger/json/main.go
  _examples/logger/with-caller/main.go
  color.go
  internal/max_text_width.go
  logger.go
  pterm.go
Labels: feature

#484 example(table): fixed text that was too long to be displayed in the animation
  _examples/table/boxed/main.go
  _examples/table/demo/main.go
  _examples/table/multiple-lines/main.go
  _examples/table/right-alignment/main.go
Labels: fix

#488 ci(workflows): Bump actions version, fix Node 12 deprecation warnings
  .github/workflows/go.yml
  .github/workflows/golangci.yml
Labels: CI

#458 feat: add optional mask to InteractiveTextInputPrinter for prompting for secrets/passwords/tokens
  _examples/interactive_textinput/password/ci.go
  _examples/interactive_textinput/password/main.go
  interactive_textinput_printer.go
  interactive_textinput_printer_test.go
Labels: feature
