Repository pterm/pterm, pull requests merged in 2023-01, with the labels that each got.

#430 refactor(progressbar): make add more safe
  progressbar_printer.go
Labels: refactor

#429 feat(multiselect): option to change checkmarks
  README.md
  _examples/interactive_multiselect/README.md
  _examples/interactive_multiselect/custom-checkmarks/README.md
  _examples/interactive_multiselect/custom-checkmarks/ci.go
  _examples/interactive_multiselect/custom-checkmarks/main.go
  atoms.go
  interactive_multiselect_printer.go
  interactive_multiselect_printer_test.go
Labels: feature

#432 feat(theme): added theme support for checkmarks
  _examples/interactive_multiselect/custom-checkmarks/main.go
  atoms.go
  interactive_multiselect_printer.go
  interactive_multiselect_printer_test.go
  theme.go
Labels: feature

#435 feat(color): added `color.ToStyle()`
  CONTRIBUTING.md
  color.go
  color_test.go
Labels: feature

#436 feat(progressbar): added optional title to `Start` method
  progressbar_printer.go
Labels: feature

#437 fix(prefix): fixed line numbers in different print functions
  prefix_printer.go
Labels: fix

#444 fix(tree): print top node #443
  _examples/tree/demo/main.go
  _examples/tree/from-leveled-list/main.go
  putils/tree_from_leveled_list.go
  tree_printer.go
Labels: fix
