Repository pterm/pterm, pull requests merged in 2024-02, with the labels that each got.

#629 fix: graceful handling of odd args
  errors.go
  logger.go
  logger_test.go
Labels: fix

#627 fix(progressbar): `Progressbar` and `Logger` did not work together co…
  logger.go
  print.go
  progressbar_printer.go
  utils_test.go
Labels: fix

#632 chore: updated PR template
  .github/pull_request_template.md
Labels: ignore-for-release

#624 fix(textinput): fixed text width calculation
  interactive_textinput_printer.go
Labels: fix, waiting for response
