Repository pterm/pterm, pull requests merged in 2025-06, with the labels that each got.

#718 chore(deps): update Go version and dependencies
  go.mod
  go.sum
Labels: ignore-for-release

#716 fix(logger): correctly print slog attribute values for json output
  logger.go
Labels: fix

#709 feat: adding more padding setters for BoxPrinter
  box_printer.go
  box_printer_test.go
Labels: feature

#719 feat(multiselect): optionally show selected options
  _examples/interactive_multiselect/show-selected-options/README.md
  _examples/interactive_multiselect/show-selected-options/main.go
  interactive_multiselect_printer.go
Labels: feature

#656 fix(spinner): Clear the old text when using `UpdateText` with `Spinner`
  spinner_printer.go
Labels: fix

#722 Fix rounding factor panic
  progressbar_printer.go
  progressbar_printer_zero_rounding_test.go
Labels: codex

#724 Fix typo in default continue prompt comment
  interactive_continue_printer.go
Labels: codex

#723 Fix comment typo in SlogHandler
  slog_handler.go
Labels: codex

#725 Fix selectOption for invalid defaults
  interactive_multiselect_printer.go
Labels: codex

#726 Fix typos in comments
  progressbar_printer_test.go
  spinner_printer_test.go
  utils_test.go
Labels: codex
